export const brandLabels = new Map([
  ['visa', 'Visa'],
  ['mastercard', 'Mastercard'],
  ['americanexpress', 'American Express'],
  ['discover', 'Discover'],
  ['dinersclub', 'Diners Club'],
  ['jcb', 'JCB'],
  ['elo', 'Elo'],
  ['visaelectron', 'Visa Electron'],
  ['maestro', 'Maestro'],
  ['forbrugsforeningen', 'Forbrugsforeningen'],
  ['dankort', 'Dankort'],
  ['hipercard', 'Hipercard'],
  ['unionpay', 'UnionPay'],
  ['laser', 'Laser'],
  ['shoppay', 'Shop Pay'],
  ['applepay', 'Apple Pay'],
  ['googlepay', 'Google Pay'],
  ['paypal', 'PayPal'],
  ['bogus', 'Bogus'],
]);
